name: cell_culture
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - ca-certificates=2018.4.16
  - chardet=3.0.4
  - confuse=1.0.0
  - htmlmin=0.1.12
  - idna=2.7
  - joblib=0.13.2
  - mccabe=0.6.1
  - missingno=0.4.2
  - more-itertools=7.2.0
  - openssl=1.0.2o
  - packaging=19.0
  - pandas-profiling=2.3.0
  - phik=0.9.8
  - pluggy=0.12.0
  - py=1.8.0
  - pycparser=2.19
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.4.0
  - pytest-pylint=0.14.1
  - pytest-remotedata=0.3.1
  - pytest-runner=5.1
  - yaml=0.1.7
  - zipp=0.5.2
  - appdirs=1.4.3
  - astroid=2.2.5
  - astropy=3.2.1
  - attrs=19.1.0
  - backcall=0.1.0
  - black=19.3b0
  - blas=1.0
  - bleach=3.1.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - click=7.0
  - colorama=0.4.1
  - cryptography=2.3
  - cryptography-vectors=2.3.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icu=58.2
  - importlib_metadata=0.17
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.0
  - isort=4.3.21
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvmlite=0.29.0
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=6.0.0
  - numba=0.45.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pandas=0.25.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.0
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pip=19.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psutil=5.6.3
  - pygments=2.4.2
  - pylint=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - pytest=5.0.1
  - python=3.7.1
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1.1
  - pyzmq=18.0.0
  - qt=5.9.6
  - qtconsole=4.5.2
  - requests=2.22.0
  - scikit-learn=0.21.1
  - scipy=1.3.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - terminado=0.8.2
  - testpath=0.4.2
  - toml=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.5.0
  - wrapt=1.11.2
  - xlrd=1.2.0
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - bokeh==1.3.1
    - fijibin==0.3.0
    - gen-utils==0.1
    - ipdb==0.12.2
    - loguru==0.3.2
    - pbr==5.1.1
    - pillow==6.1.0
    - pydebug==1.0.3
    - stevedore==1.30.0
    - virtualenv==16.1.0
    - virtualenv-clone==0.4.0
    - virtualenvwrapper==4.8.2
    - win32-setctime==1.0.1
    - xlsxwriter==1.1.8
