name: cell_culture
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas-profiling=2.3.0
  - ipykernel=5.1.1
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.0
  - jupyter=1.0.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=6.0.0
  - numba=0.45.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pandas=0.25.0
  - python=3.7.1
  - scikit-learn=0.21.1
  - scipy=1.3.0
  - seaborn=0.9.0
  - setuptools=41.0.1
  - statsmodels=0.10.1
  - pip:
    - bokeh==1.3.1
    - loguru==0.3.2
    - pbr==5.1.1
    - virtualenv==16.1.0
    - virtualenv-clone==0.4.0
    - virtualenvwrapper==4.8.2
    - xlsxwriter==1.1.8
